baseURL = 'https://zoriya.dev/'
languageCode = 'en'
paginate = 50
enableRobotsTXT = true
googleAnalytics = "G-KK12E7TNEC"
enableEmoji = false
titleCaseStyle = 'none'

[outputs]
home = ["HTML", "RSS", "JSON"]
