baseURL = 'https://zoriya.dev/'
languageCode = 'en'
paginate = 50
enableRobotsTXT = true
googleAnalytics = "G-KK12E7TNEC"
enableEmoji = true
titleCaseStyle = 'none'

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"
