title = "Zoe's blog"

[params]
# logo = "img/author.png"

[author]
name = "Zoe Roux"
image = "img/author.png"
headline = "I'm not a dev, I'm a sorceress."
bio = "I work on [Kyoo](https://github.com/zoriya/kyoo) or other nerdy projects at night."
links = [
	{ github = "https://github.com/zoriya" },
	{ linkedin = "https://www.linkedin.com/in/zoe-roux/" },
	{ twitter = "https://twitter.com/zoriya_dev" },
	{ rss = "https://zoriya.dev/index.xml" },
]
