[[main]]
  name = "Blogs"
  pageRef = "blogs"
  weight = 10

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10


[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 10


[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/zoriya"
  weight = 30

[[footer]]
  name = "Blogs"
  pageRef = "blogs"
  weight = 20

[[footer]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 20
