# colorScheme = "princess"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
smartTOC = true
robots = "all"
dateFormat = "2006-01-02"
mainSections = ["blogs", "posts"]

homepage.layout = "profile"
homepage.showRecent = true

footer.showAppearanceSwitcher = true

article.showTableOfContents = true
article.showEdit = true
article.editURL = "https://github.com/zoriya/blog/tree/master/content/"
article.showWordCount = false
article.showAuthorBottom = true
article.showTaxonomies = true
article.showRelatedContent = true
article.seriesOpened = true
article.relatedContentLimit = 3
article.showHero = true
article.showComments = true
article.heroStyle = "background"
list.showSummary = false

firebase.apiKey = "AIzaSyBjyI5DNQCdzfL0PEYXBhLgVujLG6_jA98"
firebase.authDomain =  "blog-130d3.firebaseapp.com"
firebase.projectId = "blog-130d3"
firebase.storageBucket = "blog-130d3.appspot.com"
firebase.messagingSenderId = "826830977480"
firebase.appId = "1:826830977480:web:dfceeb22a45296838ea8fd"
firebase.measurementId = "G-W0MTD9HDEG"
article.showViews = true
article.showLikes = true
